apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-chatbot
  template:
    metadata:
      labels:
        app: pdf-chatbot
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8502"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: pdf-chatbot
        image: pdf-chatbot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
        - containerPort: 8502
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: OPENAI_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"