apiVersion: v1
kind: Service
metadata:
  name: pdf-chatbot-service
  labels:
    app: pdf-chatbot
spec:
  type: NodePort
  selector:
    app: pdf-chatbot
  ports:
    - port: 8501
      targetPort: 8501
      nodePort: 30001
      name: web
    - port: 8502
      targetPort: 8502
      name: metrics